spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/first_demo
    username: root
    password: 123456789
    driver-class-name: com.mysql.jdbc.Driver

  resources:
    static-locations: classpath:/templates/

  freemarker:
    cache: false
    suffix: .ftl
    template-loader-path: classpath:/templates/
    content-type: text/html
    enabled: true
    check-template-location: true

jpa:
  hibernate:
    ddl-auto: update //自动更新
  show-sql: true  //日志中显示sql语句






