spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/first_demo
    username: root
    password: 123456789
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf: #开发时禁用缓存
    cache: false

jpa:
  hibernate:
    ddl-auto: update //自动更新
  show-sql: true  //日志中显示sql语句




